name: Go
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Install FoundationDB client
        run: |
          curl -fSSL -o foundationdb.deb https://www.foundationdb.org/downloads/7.3.43/ubuntu/installers/foundationdb-clients_7.3.43-1_amd64.deb
          sudo dpkg -i foundationdb.deb
      - name: Test
        run: go test -race -cover -test.v .
